#!/usr/bin/env bash
# Status: archived 2026-10-07 (pre-schema-v9); last runnable at ae721b7 or earlier
# exp067: plan 056 §3 — value-label arms, each a fine-tune of g_gen05 that differs only in the value
# label, judged on the frozen MC value benchmark (runs/value_bench/g05_gen06.jsonl).
#   A  --value-blend 0.5 (today's label, the control)
#   B  --value-blend 1.0 (the drive outcome alone)
#   C  --value-td-lambda 0.8
#   D  --value-td-lambda 0.95
#   E  NAME=LABEL: arm LABEL's data at --value-weight 1.0 instead of 0.25, e.g. `E=B`
#   F  MC-averaged: every train sample's outcome replaced by the mean of 8 policy-only playouts from
#      it under g_gen05 (`botbowl-ui mc-label`), then --value-blend 1.0; val is blend10's (raw outcome)
# Data: loopmix16x9g/gen07 (generated by g_gen06; unseen by g_gen05, disjoint from the benchmark's
# gen06), train shards 0-3,5,6, val shards 4,7. Train step: plan 054's (lr 5e-5, --freeze-bn
# --init-candidate --eval-at 250,500 --select-on policy), 3 epochs, cq tau 100, value weight 0.25,
# per-drive value weight, seed 1.
# Per arm: the benchmark (paired against g_gen05 and arm A), and the absorb probe against g_gen05 on
# gen07's held-out shards prepared with --value-blend 1.0, so its dvalMSE is against the raw outcome.
#
#   scripts/exp067_value_labels.sh [ARM ...]      (default: A B)
set -uo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"; cd "$REPO"
OUT="$REPO/runs/exp067"; P="$OUT/prep"; A="$OUT/arms"; mkdir -p "$P" "$A"
M="$REPO/models/az_v7"; G7="$REPO/runs/loopmix16x9g/gen07"; G05="$M/bbnet_mix16x9g_gen05"
BENCH="$REPO/runs/value_bench/g05_gen06.jsonl"
export BOARD_SIZE_W=16 BOARD_SIZE_H=9 BOARD_PLAYERS=6 CARGO_TARGET_DIR="$REPO/target/16x9"
PREPARE="$CARGO_TARGET_DIR/release/prepare"; UI="$CARGO_TARGET_DIR/release/botbowl-ui"; PY="$REPO/train/.venv/bin/python"
STATUS="$OUT/status.md"; status() { echo "[$(date '+%F %T')] $*" >> "$STATUS"; }; die() { status "FATAL: $*"; exit 1; }
git diff --quiet || die "dirty tree"
status "start: commit $(git rev-parse --short HEAD), arms ${*:-A B}"
cargo build --release -p botbowl-nn -p botbowl-ui >> "$OUT/build.log" 2>&1 || die "build"

TRAIN_IN=""; for k in 0 1 2 3 5 6; do TRAIN_IN="$TRAIN_IN $G7/shard$k.jsonl"; done
VAL_IN="$G7/shard4.jsonl $G7/shard7.jsonl"
# prep NAME LABEL_ARGS...: gen07 train + val prepared under one value label (cq tau 100 policy).
prep() {
    local name="$1"; shift
    [ -e "$P/.$name" ] && return 0
    # shellcheck disable=SC2086
    "$PREPARE" --in $TRAIN_IN --out "$P/${name}_train" --policy-target cq --tau 100 "$@" >> "$OUT/prepare.log" 2>&1 \
        && "$PREPARE" --in $VAL_IN --out "$P/${name}_val" --policy-target cq --tau 100 "$@" >> "$OUT/prepare.log" 2>&1 \
        && touch "$P/.$name" || die "prepare $name"
    status "prepared $name ($*)"
}
# arm NAME PREP [TRAIN_EXTRA...]: one fine-tune of g_gen05 with plan 054's train step.
arm() {
    local name="$1" data="$2"; shift 2
    [ -e "$A/$name.done" ] && return 0
    (cd "$REPO/train" && "$PY" -m bbnn.train --data "$P/${data}_train" --val-data "$P/${data}_val" --epochs 3 \
        --device cuda --init "$G05.pt" --lr 5e-5 --eval-every 1000 --per-drive-value-weight --seed 1 \
        --freeze-bn --init-candidate --eval-at 250,500 --select-on policy \
        --out "$A/$name.pt" --onnx "$A/$name.onnx" "$@" > "$A/$name.log" 2>&1) || die "arm $name"
    touch "$A/$name.done"
    status "arm $name: $(grep -E '^restored' "$A/$name.log" | tail -1)"
}

# mc_label: arm F's corpus and its prepared dirs (train relabelled, val = blend10's raw outcome).
mc_label() {
    local mc="$OUT/mc_gen07" sock="/tmp/bbnn-exp067-mc.sock" nn=""
    if [ ! -e "$mc/.done" ]; then
        "$PY" scripts/nn_server.py --socket "$sock" --device cuda --model "$G05.onnx" --max-models 2 \
            --stats-every 300 --canvas 11x18 >> "$OUT/mc_nn_server.log" 2>&1 & nn=$!
        for _ in $(seq 120); do [ -S "$sock" ] && break; sleep 1; done
        [ -S "$sock" ] || die "mc-label nn_server"
        status "mc-label: gen07 train shards, 8 playouts per sample under g_gen05"
        # shellcheck disable=SC2086
        "$UI" mc-label --corpus $TRAIN_IN --model "$G05.onnx" --nn-server "$sock" --playouts 8 --parallel 8 \
            --out-dir "$mc" 2>> "$OUT/mc_label.log"; local rc=$?
        kill "$nn" 2>/dev/null; wait "$nn" 2>/dev/null; rm -f "$sock"
        [ $rc -eq 0 ] || die "mc-label — see $OUT/mc_label.log"
        touch "$mc/.done"
        status "mc-label done: $(grep -c '^mc-label: .* -> ' "$OUT/mc_label.log") shards"
    fi
    if [ ! -e "$P/.mc8" ]; then
        local in=""; for k in 0 1 2 3 5 6; do in="$in $mc/shard$k.jsonl"; done
        # shellcheck disable=SC2086
        "$PREPARE" --in $in --out "$P/mc8_train" --policy-target cq --tau 100 --value-blend 1.0 >> "$OUT/prepare.log" 2>&1 \
            || die "prepare mc8"
        ln -sfn blend10_val "$P/mc8_val"; touch "$P/.mc8"
        status "prepared mc8 (MC labels, --value-blend 1.0)"
    fi
}

prep blend10 --value-blend 1.0   # also every arm's outcome-calibration val set
ARMS=("$@"); [ ${#ARMS[@]} -eq 0 ] && ARMS=(A B)
for a in "${ARMS[@]}"; do
    case "$a" in
        A) prep blend05 --value-blend 0.5; arm A blend05 --value-weight 0.25 ;;
        B) arm B blend10 --value-weight 0.25 ;;
        C) prep td080 --value-td-lambda 0.8; arm C td080 --value-weight 0.25 ;;
        D) prep td095 --value-td-lambda 0.95; arm D td095 --value-weight 0.25 ;;
        F) mc_label; arm F mc8 --value-weight 0.25 ;;
        E=A) arm E blend05 --value-weight 1.0 ;;
        E=B) arm E blend10 --value-weight 1.0 ;;
        E=C) arm E td080 --value-weight 1.0 ;;
        E=D) arm E td095 --value-weight 1.0 ;;
        *) die "unknown arm $a" ;;
    esac
done

NETS=(g05="$G05.onnx"); PTS=(); for a in A B C D E F; do
    [ -e "$A/$a.done" ] && NETS+=("$a=$A/$a.onnx") && PTS+=("$a=$A/$a.pt")
done
scripts/value_bench.sh "$BENCH" "$OUT/bench" "${NETS[@]}" > "$OUT/bench.log" 2>&1 || die "value bench"
status "benchmark: $(grep -E '^VALUE_BENCH' "$OUT/bench/summary.txt" | sed 's/^VALUE_BENCH//' | paste -sd'|')"
# The same states paired against the control instead of the generator.
VS_A=(); for a in A B C D E F; do [ -s "$OUT/bench/$a.jsonl" ] && VS_A+=("$a=$OUT/bench/$a.jsonl"); done
"$PY" scripts/value_bench_summary.py "${VS_A[@]}" > "$OUT/bench/summary_vs_A.txt" 2>&1
status "benchmark vs A: $(grep -E '^VALUE_BENCH_PAIRED' "$OUT/bench/summary_vs_A.txt" | sed 's/^VALUE_BENCH_PAIRED //' | paste -sd'|')"
"$PY" scripts/absorb_probe.py --summary --val "$P/blend10_val" generator="$G05.pt" "${PTS[@]}" \
    > "$OUT/absorb.txt" 2>&1 || status "WARN: absorb probe failed — see $OUT/absorb.txt"
status "absorb (gen07 held-out, valMSE vs raw outcome): $(grep '^ABSORB' "$OUT/absorb.txt" | sed 's/^ABSORB //' | paste -sd'|')"
status "done"
