//! Emits the board-dimension / team-size constants consumed by `core::model`.
//!
//! Board size is a *build-time* choice (plan 017): each curriculum tier is a
//! separate `cargo build`. The env vars carry the **playable** dimensions
//! (matching plan 017's tier table); we add 2 for the out-of-bounds border to
//! get the engine `WIDTH`/`HEIGHT`. Defaults reproduce today's 28x17 / 11-player
//! board exactly, so the default build is byte-identical and the test suite is
//! unaffected.

use std::{env, fs, path::Path};

fn parse(name: &str, default: usize) -> usize {
    match env::var(name) {
        Ok(v) => v
            .trim()
            .parse()
            .unwrap_or_else(|_| panic!("{name}='{v}' is not a usize")),
        Err(_) => default,
    }
}

fn main() {
    for v in ["BOARD_SIZE_W", "BOARD_SIZE_H", "BOARD_PLAYERS"] {
        println!("cargo:rerun-if-env-changed={v}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    // Playable dimensions (no OOB border). Engine consts add 2 below.
    let pw = parse("BOARD_SIZE_W", 26);
    let ph = parse("BOARD_SIZE_H", 15);
    let team_size = parse("BOARD_PLAYERS", 11);

    // WIDTH is the long (end-zone) axis and is even; HEIGHT is the cross axis
    // and is odd — i.e. playable width even, playable height odd. This keeps
    // WIDTH/2 a clean team-side split and gives HEIGHT a true centre row.
    assert!(pw >= 8 && pw % 2 == 0, "BOARD_SIZE_W must be even and >= 8, got {pw}");
    assert!(ph >= 3 && ph % 2 == 1, "BOARD_SIZE_H must be odd and >= 3, got {ph}");
    assert!(team_size >= 1, "BOARD_PLAYERS must be >= 1, got {team_size}");

    let width = pw + 2; // engine consts (with OOB border)
    let height = ph + 2;

    // Derived geometry — formulas verified to reproduce the historical literals
    // at 28x17 (los 5..=11, north 1..=4, south 12..=15) and degrade sanely on
    // smaller boards.
    let los_home_x = width / 2; // 14 @28
    let los_away_x = width / 2 - 1; // 13
    let center_y = height / 2; // 8 @17
    let half = (height - 4) / 4; // 3 @17 -> los 5..=11
    let los_lo = center_y - half; // 5
    let los_hi = center_y + half; // 11
    let north_lo = 1; // 1
    let north_hi = los_lo - 1; // 4
    let south_lo = los_hi + 1; // 12
    let south_hi = height - 2; // 15 (last playable row)

    // Fail the build (not a runtime panic) if a board combo produces empty or
    // out-of-bounds setup ranges. Holds for every tier in plan 017's table.
    let last_playable = height - 2;
    assert!(
        1 <= los_lo && los_lo <= los_hi && los_hi <= last_playable,
        "LOS y-range {los_lo}..={los_hi} invalid for height {height}"
    );
    assert!(north_lo <= north_hi, "north wing y-range {north_lo}..={north_hi} empty");
    assert!(south_lo <= south_hi, "south wing y-range {south_lo}..={south_hi} empty");

    // Kickoff-table events (Perfect Defense, Blitz!, …) assume a real formation;
    // below 7 players we use a degenerate kickoff (ball lands, no event roll).
    let kickoff_table_enabled = team_size >= 7;

    // Roster keeps one reserve over the fielded team size (12 @11).
    let roster_per_team = team_size + 1;

    let body = format!(
        "// @generated by build.rs — do not edit.
pub const WIDTH: usize = {width};
pub const HEIGHT: usize = {height};
pub const WIDTH_: Coord = WIDTH as Coord;
pub const HEIGHT_: Coord = HEIGHT as Coord;
pub const TEAM_SIZE: usize = {team_size};
pub const ROSTER_PER_TEAM: usize = {roster_per_team};
pub const KICKOFF_TABLE_ENABLED: bool = {kickoff_table_enabled};
pub const LINE_OF_SCRIMMAGE_HOME_X: Coord = {los_home_x};
pub const LINE_OF_SCRIMMAGE_AWAY_X: Coord = {los_away_x};
pub const LINE_OF_SCRIMMAGE_Y_RANGE: std::ops::RangeInclusive<Coord> = {los_lo}..={los_hi};
pub const NORTH_WING_Y_RANGE: std::ops::RangeInclusive<Coord> = {north_lo}..={north_hi};
pub const SOUTH_WING_Y_RANGE: std::ops::RangeInclusive<Coord> = {south_lo}..={south_hi};
"
    );

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("board_config.rs");
    fs::write(dest, body).unwrap();
}
