//! Emits the board-dimension / team-size constants consumed by `core::model`.
//!
//! Board size is a *build-time* choice (plan 017): each curriculum tier is a
//! separate `cargo build`. The env vars carry the **playable** dimensions
//! (matching plan 017's tier table); we add 2 for the out-of-bounds border to
//! get the engine `WIDTH`/`HEIGHT`. Defaults reproduce today's 28x17 / 11-player
//! board exactly, so the default build is byte-identical and the test suite is
//! unaffected.

use std::{env, fs, path::Path};

fn parse(name: &str, default: usize) -> usize {
    match env::var(name) {
        Ok(v) => v
            .trim()
            .parse()
            .unwrap_or_else(|_| panic!("{name}='{v}' is not a usize")),
        Err(_) => default,
    }
}

fn main() {
    for v in ["BOARD_SIZE_W", "BOARD_SIZE_H", "BOARD_PLAYERS"] {
        println!("cargo:rerun-if-env-changed={v}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    // Playable dimensions (no OOB border). Engine consts add 2 below.
    let pw = parse("BOARD_SIZE_W", 26);
    let ph = parse("BOARD_SIZE_H", 15);
    let team_size = parse("BOARD_PLAYERS", 11);

    // WIDTH is the long (end-zone) axis and must stay even: the codebase
    // mirrors states with `x -> width - 1 - x`, and that only exchanges the two
    // LOS columns (and therefore the two halves) at an even width. HEIGHT has
    // no parity rule — `BoardDims::bands` keeps the wings equal at any height.
    assert!(pw >= 8 && pw % 2 == 0, "BOARD_SIZE_W must be even and >= 8, got {pw}");
    assert!(ph >= 3, "BOARD_SIZE_H must be >= 3, got {ph}");
    assert!(team_size >= 1, "BOARD_PLAYERS must be >= 1, got {team_size}");
    // `Coord` is i8, so the engine dims (playable + 2) must fit in it.
    assert!(pw + 2 <= 127 && ph + 2 <= 127, "board {pw}x{ph} exceeds the i8 Coord range");

    let width = pw + 2; // engine consts (with OOB border)
    let height = ph + 2;

    // Roster keeps one reserve over the fielded team size (12 @11).
    let roster_per_team = team_size + 1;

    // Only the *capacity* consts are emitted — they size `FullPitch` and the
    // roster arrays and cap the runtime board. All derived gameplay geometry
    // (LOS / wing bands, kickoff-table gating, end zones) lives in `BoardDims`
    // methods so it can vary at runtime, and is validated there.
    let body = format!(
        "// @generated by build.rs — do not edit.
pub const WIDTH: usize = {width};
pub const HEIGHT: usize = {height};
pub const WIDTH_: Coord = WIDTH as Coord;
pub const HEIGHT_: Coord = HEIGHT as Coord;
pub const TEAM_SIZE: usize = {team_size};
pub const ROSTER_PER_TEAM: usize = {roster_per_team};
"
    );

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("board_config.rs");
    fs::write(dest, body).unwrap();
}
