[package]
name = "botbowl-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
botbowl-curriculum = { version = "0.1.0", path = "../botbowl-curriculum/" }
botbowl-data = { version = "0.1.0", path = "../botbowl-data/" }
botbowl-engine = { version = "0.1.0", path = "../botbowl-engine/" }
botbowl-mcts = { version = "0.1.0", path = "../botbowl-mcts/" }
botbowl-nn = { version = "0.1.0", path = "../botbowl-nn/" }
clap = { version = "4", features = ["derive"] }
crossterm = "0.27.0"
rand = "0.8.5"
rand_chacha = "0.3"
ratatui = "0.25.0"

[dev-dependencies]
insta = "1"
