#!/usr/bin/env python3
"""Plan 031 D1 follow-up: is the search's optimism a backup bug or a value-head bias?

D1 measured `E[root_value/1000 - outcome_value] = +0.133..+0.140` in the *mover's*
frame over gen05-07's `nn` shards, and +0.008 in the raw Home frame. Two mechanisms
produce exactly that, and D1 alone cannot tell them apart because the root value is
a function of the leaf values:

  (a) minimax-over-noise — the player-node backup takes max/min over noisy child Q
      (`dynamics.rs::backprop_scores`), which is biased toward the mover. This is
      what plan 032 #2 (mean backup) is written to fix.
  (b) the value head is simply biased high in its own mover-centric frame
      (`botbowl-nn/src/perspective.rs` canonicalises every board into the mover's
      view, so a constant offset there is a mover-frame offset by construction).

This separates them: run the net on the same states with **no search at all**, and
subtract. Pass the prepared dir, the checkpoint, and (optionally) the shard the
prepared dir was built from to get the paired decomposition:

    target/14x7/release/prepare --in runs/loop14x7/gen07/shard4.jsonl \
        --out runs/audit031/prep_gen07_nn
    scripts/audit_value_head_bias.py runs/audit031/prep_gen07_nn/dims_16x9 \
        models/bbnet_14x7_gen03.pt runs/loop14x7/gen07/shard4.jsonl

Use an `nn` shard (0-4) generated by the checkpoint you pass — asking a net about a
heuristic shard's roots measures something else, and heuristic `root_value` is bare
`leaf_score`, which is not even on the outcome scale.

The prepared `value.npy` is already `targets.rs::value_target` — the mover-frame
drive outcome — and the net's value head is mover-centric, so the two are directly
comparable with no sign handling. That is the same pairing `train.py` optimises.
`prepare` streams trajectories in order and (with the default `--min-root-visits 0`)
drops nothing, so `.npy` row `i` is the `i`-th sample of the shard; the script
asserts that alignment against the value targets rather than trusting it.
"""
import json
import sys

import numpy as np
import torch

sys.path.insert(0, "train/src")
from bbnn.model import BBNet  # noqa: E402

BUCKETS = [(0, 10, "<=10"), (11, 30, "11-30"), (31, 60, "31-60"), (61, 10**9, ">60")]


def predict(dims_dir, ckpt):
    spatial = np.load(f"{dims_dir}/spatial.npy", mmap_mode="r")
    glob = np.load(f"{dims_dir}/global.npy", mmap_mode="r")
    target = np.load(f"{dims_dir}/value.npy").astype(np.float64)

    sd = torch.load(ckpt, map_location="cpu")
    if isinstance(sd, dict) and "state_dict" in sd:
        sd = sd["state_dict"]
    # Defaults come from the same compile-time constants `encode.rs` writes, so a
    # shape mismatch means the checkpoint predates a schema bump — let strict=True
    # say so rather than silently scoring the wrong net.
    net = BBNet(spatial_ch=spatial.shape[1], global_f=glob.shape[1])
    net.load_state_dict(sd)
    net.eval()

    # CPU on purpose: 19k samples through a 0.48M-param net is seconds, and the
    # GPU is usually busy with a training arm when this gets run.
    preds = np.empty(len(target))
    with torch.no_grad():
        for i in range(0, len(target), 1024):
            s = torch.from_numpy(np.ascontiguousarray(spatial[i : i + 1024]))
            g = torch.from_numpy(np.ascontiguousarray(glob[i : i + 1024]))
            _, v = net(s, g)
            preds[i : i + 1024] = v.squeeze(-1).numpy()
    return preds, target, spatial.shape


def read_shard(path):
    """Mover-frame `root_value/1000`, outcome, and fan width, in file order."""
    root, outcome, fan = [], [], []
    with open(path) as f:
        for line in f:
            game = json.loads(line)
            for s in game["samples"]:
                if s["root_value"] is None:
                    continue
                sign = 1.0 if s["to_move"] == "Home" else -1.0
                root.append(sign * s["root_value"] / 1000.0)
                outcome.append(sign * s["outcome_value"])
                fan.append(len(s["children"]))
    return np.clip(np.array(root), -1, 1), np.array(outcome), np.array(fan)


def main(argv):
    if len(argv) not in (2, 3):
        sys.exit(__doc__)
    dims_dir, ckpt = argv[0], argv[1]
    shard = argv[2] if len(argv) == 3 else None

    preds, t, shape = predict(dims_dir, ckpt)
    n = len(t)
    se = lambda x: x.std(ddof=1) / np.sqrt(len(x))  # noqa: E731
    manifest = json.load(open(f"{dims_dir}/manifest.json"))
    print(f"{dims_dir}: N={n} spatial={shape}  net={ckpt} (schema v{manifest.get('nn_schema_version')})")

    leaf_gap = preds - t
    print("\n## Bare value head, no search")
    print(f"  mean predicted {preds.mean():+.4f}   mean outcome {t.mean():+.4f}")
    print(f"  **gap** {leaf_gap.mean():+.4f}  SE {se(leaf_gap):.4f}   RMSE {np.sqrt((leaf_gap ** 2).mean()):.4f}")
    b, a = np.polyfit(preds, t, 1)
    print(f"  fit outcome ~ a + b*pred:  b={b:.4f}  a={a:+.4f}   (calibrated = 1, 0)")

    print(f"\n  {'bin':<14}{'n':>8}{'mean pred':>12}{'mean outcome':>14}{'gap':>9}")
    edges = np.arange(-1.0, 1.01, 0.2)
    for lo, hi in zip(edges[:-1], edges[1:]):
        m = (preds >= lo) & (preds < hi) if hi < 1.0 else (preds >= lo)
        if m.sum():
            print(
                f"  [{lo:+.1f},{hi:+.1f}){m.sum():>8}{preds[m].mean():>12.3f}"
                f"{t[m].mean():>14.3f}{leaf_gap[m].mean():>9.3f}"
            )

    if shard is None:
        return
    root, outcome, fan = read_shard(shard)
    assert len(root) == n, f"{shard} has {len(root)} samples, prepared dir has {n}"
    assert np.abs(outcome - t).max() == 0.0, "row alignment broken: shard outcomes != value.npy"

    root_gap = root - t
    added = root - preds
    print(f"\n## Search on the identical {n} rows ({shard})")
    print(f"  bare NN leaf gap      {leaf_gap.mean():+.4f}  SE {se(leaf_gap):.4f}")
    print(f"  1000-iter search gap  {root_gap.mean():+.4f}  SE {se(root_gap):.4f}")
    print(f"  ** added by search ** {added.mean():+.4f}  SE {se(added):.4f}  z = {added.mean() / se(added):.1f}")
    print(f"  share of the search's optimism created by the search: {added.mean() / root_gap.mean():.1%}")

    print(f"\n  {'fan':<8}{'n':>8}{'leaf':>10}{'search':>10}{'added':>10}")
    for lo, hi, label in BUCKETS:
        m = (fan >= lo) & (fan <= hi)
        if m.sum():
            print(
                f"  {label:<8}{m.sum():>8}{leaf_gap[m].mean():>+10.4f}"
                f"{root_gap[m].mean():>+10.4f}{added[m].mean():>+10.4f}"
            )


if __name__ == "__main__":
    main(sys.argv[1:])
