#!/usr/bin/env bash
# Launch train_loop.sh as a from-scratch AlphaZero run.
#
# ---- restart 2026-09-16 (schema v6) ----------------------------------------
# The 2026-09-15 run (runs/az14x7, models/az) reached gen02 and is now dead
# data. Two things moved under it:
#   * the encoder: v4 (u8 raw counts) -> v5 (unpaired per-player planes, the
#     endzone planes) -> v6 (the active player's path probabilities), C 103 -> 59.
#     Every one of its checkpoints is unloadable and its prepared corpus has the
#     wrong channel count.
#   * the generator: random_start.rs now fields players with varied stat lines
#     and skills drawn from Skill::good_skills(), unconditionally, and the
#     encoder has a plane per skill to see them. Its corpus was generated by a
#     board of identical linemen — a different distribution, not just a
#     different encoding.
# runs/az14x7 and models/az are kept and untouched; nothing here reads them —
# not as a corpus, not as a warm start, not as the anchor.
#
# ---- why from random weights at all ----------------------------------------
# train_loop.sh's own gen-0 bootstrap trains its first champion on a corpus the
# *scripted* bot generated, which makes the scripted bot the teacher of
# everything downstream. This run starts from random weights instead
# (scripts/make_random_net.py) and lets search be the only source of signal —
# what AlphaZero actually specifies.
#
# What is deliberately NOT reverted to a literal AlphaZero reading:
#   * POLICY_TARGET=cq (not `visits`) — plan 032 #7. `visits` has not converged
#     at 1000 iterations over a wide fan (plan 031 D2), which is engine-
#     independent and still holds.
#   * --mode random-start, drive-bounded — the whole pipeline's value backfill
#     is drive-relative (plan 023), and it is what makes 4800 games/gen affordable.
# Both are noted so the deviation is a choice on the record, not an accident.
#
# Training-side knobs stay at the loop defaults (EPOCHS=10, plain Adam, value
# loss weight 1.0). Plan 036's W1-W6 are *not* switched on here: they are
# measured offline against this run's own prepared window and only then
# adopted, so the loop stays the baseline arm of its own A/B.
#
#   nohup scripts/az_from_scratch.sh > /dev/null 2>&1 &
#   tail -f runs/az14x7v6/status.md
#   touch runs/az14x7v6/STOP       # clean exit at the next phase boundary
set -eu

REPO="$(cd "$(dirname "$0")/.." && pwd)"

# Overridable so a smoke test can point the whole thing at a scratch dir
# without editing this file; the defaults are the real run.
export RUN_DIR="${RUN_DIR:-$REPO/runs/az14x7v6}"
export MODEL_DIR="${MODEL_DIR:-$REPO/models/az_v6}"  # never write next to the old nets
export NN_SOCKET="${NN_SOCKET:-/tmp/bbnn-az6.sock}"  # distinct from the old runs' sockets

SEED_NET="$MODEL_DIR/bbnet_14x7_gen00"

# The gen-0 champion: random weights, so train_loop.sh's heuristic bootstrap
# (which only fires when no champion exists) is skipped entirely.
if [ ! -f "$SEED_NET.onnx" ]; then
    "$REPO/train/.venv/bin/python" "$REPO/scripts/make_random_net.py" \
        --out "$SEED_NET" --seed 0
fi

export INIT_CHAMPION="$SEED_NET.onnx"
# gen01 must train from random init at SCRATCH_LR, not fine-tune the seed at
# WARM_LR. gen02+ warm-start from gen01 as usual.
export NO_WARM_FROM="$SEED_NET.pt"
# The anchor, self-healing across the first relaunch. train_loop.sh dies if the
# anchor file is missing, so gen01's eval has to run against the random seed
# net — and that measurement lasted exactly one generation last time: gen01 beat
# it 40-0-0, pinning the curve at its ceiling and taking the REGRESSION/PLATEAU
# flags with it. gen01 is the natural "progress since the first trained
# generation" baseline, so the moment it exists it becomes the anchor; no manual
# re-anchoring, and no backfill, because the generation that switches is the
# first one measured against it.
#
# Re-anchor again by hand (per plan 030: add a second, overlap three
# generations, then drop this one) once the rolling mean passes ~0.75.
# Re-anchored to gen07 on 2026-09-18. gen01 had saturated exactly as plan 030
# says to watch for: rolling3 reached 0.883 against it (gen06 alone scored
# 0.925), well past the ~0.75 trigger, so it had stopped discriminating — gen07
# reading 0.875 against gen06's 0.925 said almost nothing about the two nets.
#
# Not the literal plan-030 procedure (add a second anchor, overlap three
# generations, then drop the old one): the loop takes one ANCHOR and a second
# would double the 40-game eval every generation. The splice is instead covered
# by the `scripted` rung, which is an absolute yardstick and spans the switch.
# Read the anchor curve as two segments, gen02-07 against gen01 and gen08+
# against gen07; the rolling mean resets at the switch by construction.
#
# Pick the *strongest* net, not a middling one: anchoring to the current best
# puts the next generation near 0.5, which is where the measurement has the most
# resolving power. Re-anchor again when rolling3 passes ~0.75.
ANCHOR_GEN="${ANCHOR_GEN:-07}"
if [ -f "$MODEL_DIR/bbnet_14x7_gen$ANCHOR_GEN.onnx" ]; then
    export ANCHOR="${ANCHOR:-$MODEL_DIR/bbnet_14x7_gen$ANCHOR_GEN.onnx}"
elif [ -f "$MODEL_DIR/bbnet_14x7_gen01.onnx" ]; then
    export ANCHOR="${ANCHOR:-$MODEL_DIR/bbnet_14x7_gen01.onnx}"
else
    export ANCHOR="${ANCHOR:-$SEED_NET.onnx}"
fi
# `random` went the same way as the anchor on the previous run — gen01 swept it
# 30-0-0 — so it is off from the start here. `scripted` is the one rung doing
# work: the old gen01 scored 0.383 there, so it is both unsaturated and the only
# *absolute* yardstick on the card (every other measurement is relative to a net
# this run trained). Note it is now a harder rung than it was: the scripted bot
# plays the varied-player boards too. Drop it once it saturates.
export EVAL_RUNGS="scripted"

exec "$REPO/scripts/train_loop.sh" "$@"
