#!/usr/bin/env bash
# Plan 040 — does anything make the fine-tune learn again? (mechanism 1)
#
# Three arms, one held-out val set, one fixed step budget. The arms differ only
# in their *training pool* and their initialisation:
#
#   w3_warm     gen(N-2..N),  warm from gen(N-1).pt @ 2e-4   production baseline
#   wide_warm   gen02..genN,  warm from gen(N-1).pt @ 2e-4   the window hypothesis
#   wide_scratch gen02..genN, random init @ 1e-3             the refresh hypothesis
#
# Plan 029 measured both hypotheses on the old engine: warm+wide 0.487
# (z=-0.30), scratch+wide 0.600 (z=+2.51). So the second arm carries prior odds
# against and the third prior odds for. Both are re-measured only because every
# corpus 029 used is unreadable now and its warm CI [0.405, 0.570] does not
# exclude a real +0.05.
#
# ---- why a *step* budget, not epochs ---------------------------------------
# Plan 029 trap 2. A wider pool at a fixed epoch count takes proportionally more
# optimizer steps, so "more data wins" and "more updates wins" become
# indistinguishable. MAX_STEPS fixes the gradient descent and lets only the
# number of distinct samples those steps draw from vary. 110k matches 029's S.
#
# ---- why gen01 is excluded from the wide pool ------------------------------
# Its corpus was generated by the *random* seed net, the analogue of the gen00
# heuristic corpus plan 029 excluded from every arm. Including it would confound
# "more data" with "some very off-policy data".
#
# ---- the primary read is not a val number ----------------------------------
# It is whether the curve MOVES: the spread of val_policy/val_value across the
# run, which is the quantity that has collapsed to ~0.005/~0.009 since gen04.
# An arm that stays flat has not addressed mechanism 1 whatever its loss says,
# and buys no games.
#
#   nohup scripts/exp040_window.sh > /dev/null 2>&1 &
#   tail -f runs/exp040/exp040.log
#   touch runs/exp040/STOP
set -u

WT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$WT"
export BOARD_SIZE_W=14 BOARD_SIZE_H=7 BOARD_PLAYERS=4
export PATH="$HOME/.cargo/bin:$PATH"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$WT/target/14x7}"

MAIN="${MAIN:-/home/mattias/repos/botbowl_rust}"
RUN_DIR="${RUN_DIR:-$MAIN/runs/az14x7v6}"
OUT="${OUT:-$MAIN/runs/exp040}"
MODEL_DIR="${MODEL_DIR:-$MAIN/models/az_v6}"
GEN="${GEN:-gen08}"                       # newest generation; its val shards are the common hold-out
FIRST_WIDE="${FIRST_WIDE:-2}"             # gen01 excluded, see header
NARROW="${NARROW:-3}"                     # production WINDOW_GENS
TRAIN_SHARDS="${TRAIN_SHARDS:-0 1 2 3 5 6}"
VAL_SHARDS="${VAL_SHARDS:-4 7}"
POLICY_ARGS="${POLICY_ARGS:---policy-target cq --tau 100 --value-blend 0.5}"
MAX_STEPS="${MAX_STEPS:-110000}"
EVAL_EVERY="${EVAL_EVERY:-2500}"
TRAIN_SEED="${TRAIN_SEED:-20260918}"
WARM_LR="${WARM_LR:-2e-4}"
SCRATCH_LR="${SCRATCH_LR:-1e-3}"
# W1/W4 are production now; the pool is what varies, not the recipe.
TRAIN_RECIPE="${TRAIN_RECIPE:---value-weight 0.25 --per-drive-value-weight}"
POLL="${POLL:-60}"

PREPARE="$CARGO_TARGET_DIR/release/prepare"
PY="${PY:-$MAIN/train/.venv/bin/python}"
mkdir -p "$OUT"
LOG="$OUT/exp040.log"
log() { echo "[$(date '+%F %T')] $*" | tee -a "$LOG"; }
die() { log "FATAL: $*"; exit 1; }
stopped() { [ -e "$OUT/STOP" ] && { log "STOP present — exiting"; return 0; }; return 1; }

gen_num() { echo "${1#gen}" | sed 's/^0*//'; }
N=$(gen_num "$GEN")
INIT="$MODEL_DIR/bbnet_14x7_gen$(printf '%02d' $((N-1))).pt"

# Wait for the generation's corpus. Liveness by run-dir staleness, not pgrep:
# the loop re-execs under systemd-inhibit and shows up as plain `bash`.
STALE_MIN="${STALE_MIN:-90}"
W=0
while [ ! -e "$RUN_DIR/$GEN/.generated" ]; do
    stopped && exit 0
    [ -n "$(find "$RUN_DIR" -type f -mmin "-$STALE_MIN" -print -quit 2>/dev/null)" ] || \
        die "$RUN_DIR untouched for ${STALE_MIN}m and $GEN never generated"
    sleep "$POLL"; W=$((W+POLL))
    [ $((W % 1800)) -eq 0 ] && log "waiting for $GEN corpus ($((W/60)) min)"
done
[ "$W" -gt 0 ] && log "$GEN corpus present after $((W/60)) min"

[ -x "$PREPARE" ] || die "$PREPARE missing"
[ -f "$INIT" ] || die "warm-start net $INIT missing"

pool() {  # pool FIRST LAST SHARDS
    local first="$1" last="$2" shards="$3" out="" i g k
    for ((i=first; i<=last; i++)); do
        g=$(printf "gen%02d" "$i")
        for k in $shards; do [ -f "$RUN_DIR/$g/shard$k.jsonl" ] && out="$out $RUN_DIR/$g/shard$k.jsonl"; done
    done
    echo "$out"
}

prep() {  # prep NAME "inputs..."
    local name="$1" inputs="$2"
    local dir="$OUT/prep_$name"
    [ -d "$dir" ] && { log "prep $name exists"; return 0; }
    [ -n "$inputs" ] || die "prep $name: no inputs"
    log "prep $name: $(echo "$inputs" | wc -w) shards"
    # shellcheck disable=SC2086
    nice -n 19 "$PREPARE" --in $inputs --out "$dir.tmp" $POLICY_ARGS > "$OUT/prep_$name.log" 2>&1 \
        || die "prep $name failed"
    mv "$dir.tmp" "$dir"
    log "prep $name done: $(grep -h 'prepare done' "$OUT/prep_$name.log" | head -1)"
}

arm() {  # arm NAME PREP INIT_ARGS...
    local name="$1" prep_name="$2"; shift 2
    local tlog="$OUT/$name.train.log"
    grep -q 'restored best-val' "$tlog" 2>/dev/null && { log "arm $name already trained"; return 0; }
    local dt dv
    dt=$(ls -d "$OUT/prep_$prep_name"/dims_* | head -1)
    dv=$(ls -d "$OUT/prep_val"/dims_* | head -1)
    log "arm $name: pool $prep_name, $MAX_STEPS steps, extra: $*"
    local t0=$SECONDS
    # shellcheck disable=SC2086
    nice -n 15 "$PY" -m bbnn.train --data "$dt" --val-data "$dv" \
        --max-steps "$MAX_STEPS" --eval-every "$EVAL_EVERY" \
        --select-on combined --seed "$TRAIN_SEED" --device auto \
        $TRAIN_RECIPE "$@" \
        --out "$OUT/$name.pt" --onnx "$OUT/$name.onnx" > "$tlog" 2>&1 \
        || die "arm $name failed — see $(basename "$tlog")"
    log "arm $name done ($(((SECONDS-t0)/60)) min): $(grep 'restored best-val' "$tlog" | tail -1)"
}

log "=== plan 040: mechanism 1, on $GEN ==="
log "pools: narrow gen$(printf '%02d' $((N-NARROW+1)))-$GEN | wide gen$(printf '%02d' $FIRST_WIDE)-$GEN (gen01 excluded)"
log "budget $MAX_STEPS steps, warm init $(basename "$INIT") @ $WARM_LR, scratch @ $SCRATCH_LR, seed $TRAIN_SEED"

stopped && exit 0
prep val    "$(pool "$N" "$N" "$VAL_SHARDS")"
prep narrow "$(pool $((N-NARROW+1)) "$N" "$TRAIN_SHARDS")"
prep wide   "$(pool "$FIRST_WIDE" "$N" "$TRAIN_SHARDS")"

stopped && exit 0; arm w3_warm      narrow --init "$INIT" --lr "$WARM_LR"
stopped && exit 0; arm wide_warm    wide   --init "$INIT" --lr "$WARM_LR"
stopped && exit 0; arm wide_scratch wide   --lr "$SCRATCH_LR"

log "=== all arms done ==="
"$PY" "$WT/scripts/exp040_report.py" "$OUT" | tee -a "$LOG"
