#!/usr/bin/env bash
# Weekend generation loop for the 14x7 tier (plan 022).
#
# Regime per generation (plan 021 §Next steps 3):
#   generate (5 nn-value shards from the champion + 3 heuristic hedge shards)
#   -> prepare (train = shards 0-3,5,6; val = shards 4,7 — one of each kind)
#   -> train (best-val restore, ONNX export)
#   -> eval report card (fixed rungs + vs current champion)
#   -> promotion gate: win_rate >= 0.55 vs champion => new champion
#   On a failed gate the champion stays the generator and the loop continues
#   with fresh seeds; the rejected net + report stay on disk.
#
# On a host with no champion yet (models/ is gitignored, so a fresh clone has
# none), a one-off gen-0 bootstrap runs first: a heuristic-only corpus, prepared
# and trained the same way, becomes the initial champion. Skipped when one exists.
#
# Launch (survives logout, prevents sleep — the script re-execs itself under
# caffeinate on macOS, systemd-inhibit on Linux):
#   nohup scripts/train_loop.sh > /dev/null 2>&1 &
# Monitor over ssh:
#   tail -f runs/loop14x7/status.md          # one line per phase
#   tail -f runs/loop14x7/loop.log           # detail
#   tail -f runs/loop14x7/gen01/shard0.log   # a generator's per-game progress
# Stop cleanly:
#   touch runs/loop14x7/STOP                 # exits at the next phase boundary
# Resume after a stop/crash: just relaunch — completed phases are skipped via
# .done markers, the champion is persisted in champion.txt.

set -u

# Keep the machine awake for the whole run. macOS uses caffeinate, Linux uses
# systemd-inhibit; on a host with neither we just run (and may be suspended).
if [ -z "${TRAIN_LOOP_NOSLEEP:-}" ]; then
    export TRAIN_LOOP_NOSLEEP=1
    if command -v caffeinate >/dev/null 2>&1; then
        exec caffeinate -is "$0" "$@"
    elif command -v systemd-inhibit >/dev/null 2>&1; then
        exec systemd-inhibit --what=sleep:idle --who="train_loop.sh" \
            --why="botbowl generation loop" --mode=block "$0" "$@"
    fi
fi

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

export BOARD_SIZE_W=14 BOARD_SIZE_H=7 BOARD_PLAYERS=4

# ---- knobs (env-overridable) ------------------------------------------------
MAX_GENS="${MAX_GENS:-10}"
GAMES_PER_SHARD="${GAMES_PER_SHARD:-600}"   # 8 shards -> 4800 games/generation
MCTS_ITERS="${MCTS_ITERS:-1000}"
EVAL_GAMES="${EVAL_GAMES:-30}"              # per ladder rung, paired Home/Away
MIRROR_GAMES="${MIRROR_GAMES:-100}"         # pre-flight heuristic mirror match
EPOCHS="${EPOCHS:-10}"
GATE="${GATE:-0.55}"                        # promotion: win_rate vs champion
TRAIN_DEVICE="${TRAIN_DEVICE:-auto}"        # trainer device: auto|cpu|cuda|cuda:N
BOOTSTRAP_GAMES_PER_SHARD="${BOOTSTRAP_GAMES_PER_SHARD:-$GAMES_PER_SHARD}"
                                            # gen-0 corpus when no champion exists
INIT_CHAMPION="${INIT_CHAMPION:-$REPO/models/bbnet_14x7_db.onnx}"
# Plan 024: batched GPU inference. `off` keeps the loop exactly as it was
# (tract on the CPU, no Python, no GPU during generate). Measured on this
# host at 8 shards x 4 parallel games: 2.62 s/game against tract's 9.93,
# i.e. 3.8x, using 4.3 cores against 5.3.
NN_SERVER="${NN_SERVER:-on}"                # on|off
NN_SOCKET="${NN_SOCKET:-/tmp/bbnn-loop.sock}"
# Concurrent games per *nn* shard. RAM-bound, not speed-bound: each
# in-flight game holds its own MCTS tree, and a tree high-waters around
# 400-500 MB at 1000 iters on this tier. Measured over 10 min in the exact
# production shape (5 nn + 3 heuristic + server) on this 15 GB box:
#   P=4 -> nn shards ~8.0 GB, 10.6 GB total, only 3 GB available  <-- too tight
#   P=2 -> ~7 GB total, 5-6 GB available, and barely slower
# Plans 020/021 record real OOM kills here, so 2 it is. Raise it on a box
# with more RAM: the throughput sweep peaked at 4.
PARALLEL_GAMES="${PARALLEL_GAMES:-2}"
NN_SERVER_RESTARTS="${NN_SERVER_RESTARTS:-3}"
SEED_BASE=10000000                          # gen G shard K: BASE + G*1e6 + K*1e5
                                            # (old corpora used 8e5.. and 2e6..)
RUN_DIR="${RUN_DIR:-$REPO/runs/loop14x7}"   # override both for dry runs so a
MODEL_DIR="${MODEL_DIR:-$REPO/models}"      # test never touches real models/
# -----------------------------------------------------------------------------

NN_SHARDS="0 1 2 3 4"       # generated by the champion (nn-value)
HEUR_SHARDS="5 6 7"         # heuristic hedge (~37% of games)
TRAIN_SHARDS="0 1 2 3 5 6"
VAL_SHARDS="4 7"            # held out whole: one nn shard + one heuristic shard

# Board size is a *build-time* choice (botbowl-engine/build.rs), so the 14x7
# binaries and a default-board `cargo test --workspace` would otherwise evict
# each other from a shared target dir and force a full rebuild on every switch.
# Nested under /target so the existing .gitignore entry still covers it.
CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$REPO/target/14x7}"
export CARGO_TARGET_DIR
UI="$CARGO_TARGET_DIR/release/botbowl-ui"
PREPARE="$CARGO_TARGET_DIR/release/prepare"
PY="$REPO/train/.venv/bin/python"
SUMMARY="$REPO/scripts/eval_summary.py"

mkdir -p "$RUN_DIR" "$MODEL_DIR"
LOG="$RUN_DIR/loop.log"
STATUS="$RUN_DIR/status.md"
CHAMPION_FILE="$RUN_DIR/champion.txt"

log() { echo "[$(date '+%F %T')] $*" >> "$LOG"; }
status() { echo "[$(date '+%F %T')] $*" >> "$STATUS"; log "STATUS: $*"; }
die() { status "FATAL: $*"; exit 1; }
check_stop() {
    if [ -e "$RUN_DIR/STOP" ]; then
        status "STOP file present — exiting cleanly ($1)"
        exit 0
    fi
}
champion() { cat "$CHAMPION_FILE"; }
# Free disk in GiB. `df -g` is macOS-only; -BG/-k are the portable GNU spellings.
free_gb() {
    if df -BG . >/dev/null 2>&1; then
        df -BG . | awk 'NR==2{gsub(/G/,"",$4); print $4"G"}'
    else
        df -k . | awk 'NR==2{printf "%dG", $4/1048576}'
    fi
}

# ---- nn sidecar lifecycle (plan 024 Stage 5) --------------------------------
# One server for the whole phase, torn down before the train phase so the
# trainer gets the whole card. A dead server is *not* fatal: the Rust client
# falls back to tract, so a shard gets slower but still finishes, which
# preserves the loop's existing "a dead shard is a warning" semantics.
NN_SERVER_PID=""
nn_server_start() {
    [ "$NN_SERVER" = "on" ] || return 0
    local model="$1"
    [ -f "${model%.onnx}.pt" ] || {
        status "WARN: no ${model%.onnx}.pt beside the champion — sidecar needs the trainer's own weights; running on tract"
        return 0
    }
    rm -f "$NN_SOCKET"
    "$PY" "$REPO/scripts/nn_server.py" --socket "$NN_SOCKET" --device cuda \
        --model "$model" --stats-every 300 >> "$RUN_DIR/nn_server.log" 2>&1 &
    NN_SERVER_PID=$!
    # Warm-up loads the net, traces it and captures 12 CUDA graphs; the
    # socket only appears once the batcher is ready, so waiting for the
    # socket is exactly the right readiness signal.
    local i=0
    while [ ! -S "$NN_SOCKET" ]; do
        i=$((i + 1))
        if [ "$i" -gt 120 ] || ! kill -0 "$NN_SERVER_PID" 2>/dev/null; then
            status "WARN: nn_server did not come up in ${i}s — see nn_server.log; shards will use tract"
            NN_SERVER_PID=""
            return 0
        fi
        sleep 1
    done
    status "nn_server up (pid $NN_SERVER_PID, $(basename "$model"), socket $NN_SOCKET)"
}
nn_server_stop() {
    [ -n "$NN_SERVER_PID" ] || return 0
    kill "$NN_SERVER_PID" 2>/dev/null
    wait "$NN_SERVER_PID" 2>/dev/null
    status "nn_server stopped (pid $NN_SERVER_PID)"
    NN_SERVER_PID=""
    rm -f "$NN_SOCKET"
}
# Never leave a server (and its 400 MB of VRAM) behind on any exit path.
trap nn_server_stop EXIT INT TERM

[ -f "$CHAMPION_FILE" ] || echo "$INIT_CHAMPION" > "$CHAMPION_FILE"
[ -x "$PY" ] || die "trainer venv python not found: $PY"
# NB: the champion file may point at a model that does not exist yet — the gen-0
# bootstrap below creates one. The hard check lives after that block.

if [ -f "$(champion)" ]; then
    CHAMP_DESC="champion $(basename "$(champion)")"
else
    CHAMP_DESC="no champion yet — will bootstrap gen-0 from a heuristic corpus"
fi
status "loop start: commit $(git rev-parse --short HEAD)$(git diff --quiet || echo -dirty), $CHAMP_DESC, ${GAMES_PER_SHARD}x8 games/gen, gate $GATE, max $MAX_GENS gens"

# ---- build ------------------------------------------------------------------
# The documented launch is `nohup scripts/train_loop.sh &`, which gets a
# non-interactive shell — and rustup's PATH line lives in the interactive
# part of most profiles, so `cargo` is typically *not* on PATH here even
# though it is in the terminal you launched from. Put it back rather than
# dying 30 seconds into a multi-day run.
case ":$PATH:" in
    *":$HOME/.cargo/bin:"*) ;;
    *) [ -x "$HOME/.cargo/bin/cargo" ] && export PATH="$HOME/.cargo/bin:$PATH" ;;
esac
command -v cargo >/dev/null 2>&1 || die "cargo not on PATH (looked in \$HOME/.cargo/bin) — cannot build"

log "building release binaries (14x7) with $(cargo --version)"
if ! cargo build --release -p botbowl-ui -p botbowl-nn >> "$LOG" 2>&1; then
    die "cargo build failed — see loop.log"
fi
[ -x "$UI" ] && [ -x "$PREPARE" ] || die "expected binaries missing after build"
status "build ok"

# ---- pre-flight: heuristic mirror match (plan 021 open issue 5) --------------
check_stop "before mirror match"
if [ ! -e "$RUN_DIR/.mirror.done" ]; then
    SECONDS=0
    status "mirror match: $MIRROR_GAMES heuristic-vs-heuristic games starting"
    if ! "$UI" eval --evaluator heuristic --mcts-iters "$MCTS_ITERS" \
            --games "$MIRROR_GAMES" --seed 424242 \
            --skip-lectures --skip-fixed-rungs \
            --vs-evaluator heuristic \
            --out "$RUN_DIR/mirror.json" > "$RUN_DIR/mirror.log" 2>&1; then
        die "mirror match failed — see mirror.log"
    fi
    status "mirror match done ($((SECONDS / 60)) min): $("$PY" "$SUMMARY" "$RUN_DIR/mirror.json")"
    touch "$RUN_DIR/.mirror.done"
fi

# ---- gen-0 bootstrap --------------------------------------------------------
# The loop needs a champion to generate from, but `models/` is gitignored, so a
# fresh clone has none. Rather than making a hand-copied .onnx a hard
# prerequisite, build one here the same way plan 020/021 built the original: a
# heuristic-only corpus (the teacher), prepared with the same train/val shard
# split, trained with best-val restore. Skipped entirely when a champion exists,
# so hosts that already have one are unaffected.
if [ ! -f "$(champion)" ]; then
    check_stop "before gen-0 bootstrap"
    GEN_DIR="$RUN_DIR/gen00"
    MODEL="$MODEL_DIR/bbnet_14x7_gen00"
    mkdir -p "$GEN_DIR"
    status "gen-0 bootstrap: $(basename "$(champion)") not found — building a champion from a heuristic corpus"

    if [ ! -e "$GEN_DIR/.generated" ]; then
        SECONDS=0
        status "gen00 generate: 8x$BOOTSTRAP_GAMES_PER_SHARD heuristic games, disk free $(free_gb)"
        PIDS=""
        for K in $NN_SHARDS $HEUR_SHARDS; do
            SEED=$((SEED_BASE + K * 100000))     # G=0 — disjoint from every gen
            "$UI" dataset --mode random-start --games "$BOOTSTRAP_GAMES_PER_SHARD" \
                --seed "$SEED" --mcts-iters "$MCTS_ITERS" --evaluator heuristic \
                --truncate --out "$GEN_DIR/shard$K.jsonl" \
                > "$GEN_DIR/shard$K.log" 2>&1 &
            PIDS="$PIDS $!:$K"
        done
        for P in $PIDS; do
            PID="${P%%:*}"; K="${P##*:}"
            if ! wait "$PID"; then
                log "WARN: gen00 shard$K generator exited nonzero (partial shard kept)"
            fi
        done
        GAMES=0
        for K in $NN_SHARDS $HEUR_SHARDS; do
            [ -s "$GEN_DIR/shard$K.jsonl" ] || die "gen00 shard$K.jsonl empty/missing — see shard$K.log"
            GAMES=$((GAMES + $(wc -l < "$GEN_DIR/shard$K.jsonl")))
        done
        status "gen00 generate done ($((SECONDS / 60)) min): $GAMES/$((BOOTSTRAP_GAMES_PER_SHARD * 8)) games"
        touch "$GEN_DIR/.generated"
    fi

    if [ ! -e "$GEN_DIR/.prepared" ]; then
        SECONDS=0
        TRAIN_IN=""; VAL_IN=""
        for K in $TRAIN_SHARDS; do TRAIN_IN="$TRAIN_IN $GEN_DIR/shard$K.jsonl"; done
        for K in $VAL_SHARDS; do VAL_IN="$VAL_IN $GEN_DIR/shard$K.jsonl"; done
        # shellcheck disable=SC2086
        "$PREPARE" --in $TRAIN_IN --out "$GEN_DIR/prepared_train" >> "$LOG" 2>&1 \
            || die "gen00 prepare (train) failed"
        # shellcheck disable=SC2086
        "$PREPARE" --in $VAL_IN --out "$GEN_DIR/prepared_val" >> "$LOG" 2>&1 \
            || die "gen00 prepare (val) failed"
        status "gen00 prepare done ($((SECONDS / 60)) min)"
        touch "$GEN_DIR/.prepared"
    fi
    DIMS_TRAIN=$(ls -d "$GEN_DIR"/prepared_train/dims_* 2>/dev/null | head -1)
    DIMS_VAL=$(ls -d "$GEN_DIR"/prepared_val/dims_* 2>/dev/null | head -1)
    [ -n "$DIMS_TRAIN" ] && [ -n "$DIMS_VAL" ] || die "gen00 prepared dims dirs missing"

    if [ ! -e "$GEN_DIR/.trained" ]; then
        SECONDS=0
        if ! "$PY" -m bbnn.train --data "$DIMS_TRAIN" --val-data "$DIMS_VAL" \
                --epochs "$EPOCHS" --device "$TRAIN_DEVICE" \
                --out "$MODEL.pt" --onnx "$MODEL.onnx" \
                > "$GEN_DIR/train.log" 2>&1; then
            die "gen00 training failed — see train.log"
        fi
        BEST=$(grep 'restored best-val weights' "$GEN_DIR/train.log" | tail -1)
        status "gen00 train done ($((SECONDS / 60)) min): ${BEST:-best-val line not found}"
        touch "$GEN_DIR/.trained"
    fi
    [ -f "$MODEL.onnx" ] || die "gen00 onnx export missing: $MODEL.onnx"

    # No promotion gate: with no incumbent, this net *is* the champion. Its
    # strength is measured by gen01's report card against the fixed rungs.
    echo "$MODEL.onnx" > "$CHAMPION_FILE"
    status "gen-0 bootstrap done: champion is now $(basename "$MODEL.onnx")"
fi

[ -f "$(champion)" ] || die "champion model not found: $(champion)"

# ---- generation loop ----------------------------------------------------------
G=1
while [ "$G" -le "$MAX_GENS" ]; do
    GG=$(printf 'gen%02d' "$G")
    GEN_DIR="$RUN_DIR/$GG"
    MODEL="$MODEL_DIR/bbnet_14x7_$GG"
    mkdir -p "$GEN_DIR"

    # -- 1. generate ----------------------------------------------------------
    check_stop "before $GG generate"
    if [ ! -e "$GEN_DIR/.generated" ]; then
        SECONDS=0
        CHAMP="$(champion)"
        nn_server_start "$CHAMP"
        # Only the nn shards talk to the sidecar, and only they get
        # parallel games: a heuristic shard has no NN call to batch, so
        # extra games there would just take cores away from the ones that
        # do. `--nn-server` is harmless if the server never came up (the
        # client falls back to tract and warns once).
        if [ -n "$NN_SERVER_PID" ]; then
            NN_EXTRA="--nn-server $NN_SOCKET --parallel-games $PARALLEL_GAMES"
        else
            NN_EXTRA=""
        fi
        status "$GG generate: 8x$GAMES_PER_SHARD games (nn-value: $(basename "$CHAMP")${NN_EXTRA:+ via sidecar x$PARALLEL_GAMES} + heuristic hedge), disk free $(free_gb)"
        PIDS=""
        for K in $NN_SHARDS $HEUR_SHARDS; do
            SEED=$((SEED_BASE + G * 1000000 + K * 100000))
            case " $NN_SHARDS " in
                *" $K "*) EV_ARGS="--evaluator nn-value --model $CHAMP $NN_EXTRA" ;;
                *)        EV_ARGS="--evaluator heuristic" ;;
            esac
            # shellcheck disable=SC2086
            "$UI" dataset --mode random-start --games "$GAMES_PER_SHARD" \
                --seed "$SEED" --mcts-iters "$MCTS_ITERS" $EV_ARGS \
                --truncate --out "$GEN_DIR/shard$K.jsonl" \
                > "$GEN_DIR/shard$K.log" 2>&1 &
            PIDS="$PIDS $!:$K"
        done
        for P in $PIDS; do
            PID="${P%%:*}"; K="${P##*:}"
            if ! wait "$PID"; then
                log "WARN: $GG shard$K generator exited nonzero (partial shard kept)"
            fi
        done
        # A shard that silently ran on tract all generation is the failure
        # this phase can otherwise hide: it finishes, its corpus is
        # correct, and it is just 4x slower. Surface it.
        FELL_BACK=$(grep -l 'NN_SERVER_FALLBACK' "$GEN_DIR"/shard*.log 2>/dev/null | wc -l)
        [ "$FELL_BACK" -eq 0 ] || status "WARN: $GG had $FELL_BACK shard(s) fall back to tract — see shard*.log and nn_server.log"
        # The trainer needs the whole card; never let the two contend.
        nn_server_stop
        GAMES=0
        for K in $NN_SHARDS $HEUR_SHARDS; do
            [ -s "$GEN_DIR/shard$K.jsonl" ] || die "$GG shard$K.jsonl empty/missing — see shard$K.log"
            GAMES=$((GAMES + $(wc -l < "$GEN_DIR/shard$K.jsonl")))
        done
        status "$GG generate done ($((SECONDS / 60)) min): $GAMES/$((GAMES_PER_SHARD * 8)) games"
        touch "$GEN_DIR/.generated"
    fi

    # -- 2. prepare -----------------------------------------------------------
    check_stop "before $GG prepare"
    if [ ! -e "$GEN_DIR/.prepared" ]; then
        SECONDS=0
        TRAIN_IN=""; VAL_IN=""
        for K in $TRAIN_SHARDS; do TRAIN_IN="$TRAIN_IN $GEN_DIR/shard$K.jsonl"; done
        for K in $VAL_SHARDS; do VAL_IN="$VAL_IN $GEN_DIR/shard$K.jsonl"; done
        # shellcheck disable=SC2086
        "$PREPARE" --in $TRAIN_IN --out "$GEN_DIR/prepared_train" >> "$LOG" 2>&1 \
            || die "$GG prepare (train) failed"
        # shellcheck disable=SC2086
        "$PREPARE" --in $VAL_IN --out "$GEN_DIR/prepared_val" >> "$LOG" 2>&1 \
            || die "$GG prepare (val) failed"
        status "$GG prepare done ($((SECONDS / 60)) min)"
        touch "$GEN_DIR/.prepared"
    fi
    DIMS_TRAIN=$(ls -d "$GEN_DIR"/prepared_train/dims_* 2>/dev/null | head -1)
    DIMS_VAL=$(ls -d "$GEN_DIR"/prepared_val/dims_* 2>/dev/null | head -1)
    [ -n "$DIMS_TRAIN" ] && [ -n "$DIMS_VAL" ] || die "$GG prepared dims dirs missing"

    # -- 3. train ---------------------------------------------------------------
    check_stop "before $GG train"
    if [ ! -e "$GEN_DIR/.trained" ]; then
        SECONDS=0
        if ! "$PY" -m bbnn.train --data "$DIMS_TRAIN" --val-data "$DIMS_VAL" \
                --epochs "$EPOCHS" --device "$TRAIN_DEVICE" \
                --out "$MODEL.pt" --onnx "$MODEL.onnx" \
                > "$GEN_DIR/train.log" 2>&1; then
            die "$GG training failed — see train.log"
        fi
        BEST=$(grep 'restored best-val weights' "$GEN_DIR/train.log" | tail -1)
        status "$GG train done ($((SECONDS / 60)) min): ${BEST:-best-val line not found}"
        touch "$GEN_DIR/.trained"
    fi
    [ -f "$MODEL.onnx" ] || die "$GG onnx export missing: $MODEL.onnx"

    # -- 4. eval report card + promotion gate ----------------------------------
    check_stop "before $GG eval"
    if [ ! -e "$GEN_DIR/.evaluated" ]; then
        SECONDS=0
        CHAMP="$(champion)"
        status "$GG eval: $EVAL_GAMES games/rung (random, scripted, mcts-heuristic, vs $(basename "$CHAMP"))"
        if ! "$UI" eval --evaluator nn-value --model "$MODEL.onnx" \
                --mcts-iters "$MCTS_ITERS" --games "$EVAL_GAMES" --seed 0 \
                --skip-lectures \
                --vs-evaluator nn-value --vs-model "$CHAMP" \
                --out "$GEN_DIR/report.json" > "$GEN_DIR/eval.log" 2>&1; then
            die "$GG eval failed — see eval.log"
        fi
        touch "$GEN_DIR/.evaluated"
    else
        SECONDS=0
    fi

    SUMMARY_LINE=$("$PY" "$SUMMARY" "$GEN_DIR/report.json" --gate "$GATE")
    GATE_RC=$?
    if [ "$GATE_RC" -eq 0 ]; then
        echo "$MODEL.onnx" > "$CHAMPION_FILE"
        echo "PROMOTED" > "$GEN_DIR/verdict"
        status "$GG eval done ($((SECONDS / 60)) min): $SUMMARY_LINE => PROMOTED, champion is now $(basename "$MODEL.onnx")"
    elif [ "$GATE_RC" -eq 2 ]; then
        echo "REJECTED" > "$GEN_DIR/verdict"
        status "$GG eval done ($((SECONDS / 60)) min): $SUMMARY_LINE => REJECTED (gate $GATE), champion stays $(basename "$(champion)")"
    else
        die "$GG gate check failed (eval_summary rc=$GATE_RC)"
    fi

    G=$((G + 1))
done

status "loop finished: $MAX_GENS generations done, champion $(basename "$(champion)")"
