#!/usr/bin/env bash
# Weekend generation loop for the 14x7 tier (plan 022).
#
# Regime per generation (plan 021 §Next steps 3):
#   generate (5 nn-value shards from the champion + 3 heuristic hedge shards)
#   -> prepare (train = shards 0-3,5,6; val = shards 4,7 — one of each kind)
#   -> train (best-val restore, ONNX export)
#   -> eval report card (fixed rungs + vs current champion)
#   -> promotion gate: win_rate >= 0.55 vs champion => new champion
#   On a failed gate the champion stays the generator and the loop continues
#   with fresh seeds; the rejected net + report stay on disk.
#
# Launch (survives logout, prevents sleep — script re-execs under caffeinate):
#   nohup scripts/train_loop.sh > /dev/null 2>&1 &
# Monitor over ssh:
#   tail -f runs/loop14x7/status.md          # one line per phase
#   tail -f runs/loop14x7/loop.log           # detail
#   tail -f runs/loop14x7/gen01/shard0.log   # a generator's per-game progress
# Stop cleanly:
#   touch runs/loop14x7/STOP                 # exits at the next phase boundary
# Resume after a stop/crash: just relaunch — completed phases are skipped via
# .done markers, the champion is persisted in champion.txt.

set -u

# Keep the machine awake for the whole run.
if [ -z "${TRAIN_LOOP_CAFFEINATED:-}" ] && command -v caffeinate >/dev/null 2>&1; then
    export TRAIN_LOOP_CAFFEINATED=1
    exec caffeinate -is "$0" "$@"
fi

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

export BOARD_SIZE_W=14 BOARD_SIZE_H=7 BOARD_PLAYERS=4

# ---- knobs (env-overridable) ------------------------------------------------
MAX_GENS="${MAX_GENS:-10}"
GAMES_PER_SHARD="${GAMES_PER_SHARD:-600}"   # 8 shards -> 4800 games/generation
MCTS_ITERS="${MCTS_ITERS:-1000}"
EVAL_GAMES="${EVAL_GAMES:-30}"              # per ladder rung, paired Home/Away
MIRROR_GAMES="${MIRROR_GAMES:-100}"         # pre-flight heuristic mirror match
EPOCHS="${EPOCHS:-10}"
GATE="${GATE:-0.55}"                        # promotion: win_rate vs champion
INIT_CHAMPION="${INIT_CHAMPION:-$REPO/models/bbnet_14x7_db.onnx}"
SEED_BASE=10000000                          # gen G shard K: BASE + G*1e6 + K*1e5
                                            # (old corpora used 8e5.. and 2e6..)
RUN_DIR="${RUN_DIR:-$REPO/runs/loop14x7}"   # override both for dry runs so a
MODEL_DIR="${MODEL_DIR:-$REPO/models}"      # test never touches real models/
# -----------------------------------------------------------------------------

NN_SHARDS="0 1 2 3 4"       # generated by the champion (nn-value)
HEUR_SHARDS="5 6 7"         # heuristic hedge (~37% of games)
TRAIN_SHARDS="0 1 2 3 5 6"
VAL_SHARDS="4 7"            # held out whole: one nn shard + one heuristic shard

UI="$REPO/target/release/botbowl-ui"
PREPARE="$REPO/target/release/prepare"
PY="$REPO/train/.venv/bin/python"
SUMMARY="$REPO/scripts/eval_summary.py"

mkdir -p "$RUN_DIR" "$MODEL_DIR"
LOG="$RUN_DIR/loop.log"
STATUS="$RUN_DIR/status.md"
CHAMPION_FILE="$RUN_DIR/champion.txt"

log() { echo "[$(date '+%F %T')] $*" >> "$LOG"; }
status() { echo "[$(date '+%F %T')] $*" >> "$STATUS"; log "STATUS: $*"; }
die() { status "FATAL: $*"; exit 1; }
check_stop() {
    if [ -e "$RUN_DIR/STOP" ]; then
        status "STOP file present — exiting cleanly ($1)"
        exit 0
    fi
}
champion() { cat "$CHAMPION_FILE"; }

[ -f "$CHAMPION_FILE" ] || echo "$INIT_CHAMPION" > "$CHAMPION_FILE"
[ -f "$(champion)" ] || die "champion model not found: $(champion)"
[ -x "$PY" ] || die "trainer venv python not found: $PY"

status "loop start: commit $(git rev-parse --short HEAD)$(git diff --quiet || echo -dirty), champion $(basename "$(champion)"), ${GAMES_PER_SHARD}x8 games/gen, gate $GATE, max $MAX_GENS gens"

# ---- build ------------------------------------------------------------------
log "building release binaries (14x7)"
if ! cargo build --release -p botbowl-ui -p botbowl-nn >> "$LOG" 2>&1; then
    die "cargo build failed — see loop.log"
fi
[ -x "$UI" ] && [ -x "$PREPARE" ] || die "expected binaries missing after build"
status "build ok"

# ---- pre-flight: heuristic mirror match (plan 021 open issue 5) --------------
check_stop "before mirror match"
if [ ! -e "$RUN_DIR/.mirror.done" ]; then
    SECONDS=0
    status "mirror match: $MIRROR_GAMES heuristic-vs-heuristic games starting"
    if ! "$UI" eval --evaluator heuristic --mcts-iters "$MCTS_ITERS" \
            --games "$MIRROR_GAMES" --seed 424242 \
            --skip-lectures --skip-fixed-rungs \
            --vs-evaluator heuristic \
            --out "$RUN_DIR/mirror.json" > "$RUN_DIR/mirror.log" 2>&1; then
        die "mirror match failed — see mirror.log"
    fi
    status "mirror match done ($((SECONDS / 60)) min): $("$PY" "$SUMMARY" "$RUN_DIR/mirror.json")"
    touch "$RUN_DIR/.mirror.done"
fi

# ---- generation loop ----------------------------------------------------------
G=1
while [ "$G" -le "$MAX_GENS" ]; do
    GG=$(printf 'gen%02d' "$G")
    GEN_DIR="$RUN_DIR/$GG"
    MODEL="$MODEL_DIR/bbnet_14x7_$GG"
    mkdir -p "$GEN_DIR"

    # -- 1. generate ----------------------------------------------------------
    check_stop "before $GG generate"
    if [ ! -e "$GEN_DIR/.generated" ]; then
        SECONDS=0
        CHAMP="$(champion)"
        status "$GG generate: 8x$GAMES_PER_SHARD games (nn-value: $(basename "$CHAMP") + heuristic hedge), disk free $(df -g . | awk 'NR==2{print $4}')G"
        PIDS=""
        for K in $NN_SHARDS $HEUR_SHARDS; do
            SEED=$((SEED_BASE + G * 1000000 + K * 100000))
            case " $NN_SHARDS " in
                *" $K "*) EV_ARGS="--evaluator nn-value --model $CHAMP" ;;
                *)        EV_ARGS="--evaluator heuristic" ;;
            esac
            # shellcheck disable=SC2086
            "$UI" dataset --mode random-start --games "$GAMES_PER_SHARD" \
                --seed "$SEED" --mcts-iters "$MCTS_ITERS" $EV_ARGS \
                --truncate --out "$GEN_DIR/shard$K.jsonl" \
                > "$GEN_DIR/shard$K.log" 2>&1 &
            PIDS="$PIDS $!:$K"
        done
        for P in $PIDS; do
            PID="${P%%:*}"; K="${P##*:}"
            if ! wait "$PID"; then
                log "WARN: $GG shard$K generator exited nonzero (partial shard kept)"
            fi
        done
        GAMES=0
        for K in $NN_SHARDS $HEUR_SHARDS; do
            [ -s "$GEN_DIR/shard$K.jsonl" ] || die "$GG shard$K.jsonl empty/missing — see shard$K.log"
            GAMES=$((GAMES + $(wc -l < "$GEN_DIR/shard$K.jsonl")))
        done
        status "$GG generate done ($((SECONDS / 60)) min): $GAMES/$((GAMES_PER_SHARD * 8)) games"
        touch "$GEN_DIR/.generated"
    fi

    # -- 2. prepare -----------------------------------------------------------
    check_stop "before $GG prepare"
    if [ ! -e "$GEN_DIR/.prepared" ]; then
        SECONDS=0
        TRAIN_IN=""; VAL_IN=""
        for K in $TRAIN_SHARDS; do TRAIN_IN="$TRAIN_IN $GEN_DIR/shard$K.jsonl"; done
        for K in $VAL_SHARDS; do VAL_IN="$VAL_IN $GEN_DIR/shard$K.jsonl"; done
        # shellcheck disable=SC2086
        "$PREPARE" --in $TRAIN_IN --out "$GEN_DIR/prepared_train" >> "$LOG" 2>&1 \
            || die "$GG prepare (train) failed"
        # shellcheck disable=SC2086
        "$PREPARE" --in $VAL_IN --out "$GEN_DIR/prepared_val" >> "$LOG" 2>&1 \
            || die "$GG prepare (val) failed"
        status "$GG prepare done ($((SECONDS / 60)) min)"
        touch "$GEN_DIR/.prepared"
    fi
    DIMS_TRAIN=$(ls -d "$GEN_DIR"/prepared_train/dims_* 2>/dev/null | head -1)
    DIMS_VAL=$(ls -d "$GEN_DIR"/prepared_val/dims_* 2>/dev/null | head -1)
    [ -n "$DIMS_TRAIN" ] && [ -n "$DIMS_VAL" ] || die "$GG prepared dims dirs missing"

    # -- 3. train ---------------------------------------------------------------
    check_stop "before $GG train"
    if [ ! -e "$GEN_DIR/.trained" ]; then
        SECONDS=0
        if ! "$PY" -m bbnn.train --data "$DIMS_TRAIN" --val-data "$DIMS_VAL" \
                --epochs "$EPOCHS" --out "$MODEL.pt" --onnx "$MODEL.onnx" \
                > "$GEN_DIR/train.log" 2>&1; then
            die "$GG training failed — see train.log"
        fi
        BEST=$(grep 'restored best-val weights' "$GEN_DIR/train.log" | tail -1)
        status "$GG train done ($((SECONDS / 60)) min): ${BEST:-best-val line not found}"
        touch "$GEN_DIR/.trained"
    fi
    [ -f "$MODEL.onnx" ] || die "$GG onnx export missing: $MODEL.onnx"

    # -- 4. eval report card + promotion gate ----------------------------------
    check_stop "before $GG eval"
    if [ ! -e "$GEN_DIR/.evaluated" ]; then
        SECONDS=0
        CHAMP="$(champion)"
        status "$GG eval: $EVAL_GAMES games/rung (random, scripted, mcts-heuristic, vs $(basename "$CHAMP"))"
        if ! "$UI" eval --evaluator nn-value --model "$MODEL.onnx" \
                --mcts-iters "$MCTS_ITERS" --games "$EVAL_GAMES" --seed 0 \
                --skip-lectures \
                --vs-evaluator nn-value --vs-model "$CHAMP" \
                --out "$GEN_DIR/report.json" > "$GEN_DIR/eval.log" 2>&1; then
            die "$GG eval failed — see eval.log"
        fi
        touch "$GEN_DIR/.evaluated"
    else
        SECONDS=0
    fi

    SUMMARY_LINE=$("$PY" "$SUMMARY" "$GEN_DIR/report.json" --gate "$GATE")
    GATE_RC=$?
    if [ "$GATE_RC" -eq 0 ]; then
        echo "$MODEL.onnx" > "$CHAMPION_FILE"
        echo "PROMOTED" > "$GEN_DIR/verdict"
        status "$GG eval done ($((SECONDS / 60)) min): $SUMMARY_LINE => PROMOTED, champion is now $(basename "$MODEL.onnx")"
    elif [ "$GATE_RC" -eq 2 ]; then
        echo "REJECTED" > "$GEN_DIR/verdict"
        status "$GG eval done ($((SECONDS / 60)) min): $SUMMARY_LINE => REJECTED (gate $GATE), champion stays $(basename "$(champion)")"
    else
        die "$GG gate check failed (eval_summary rc=$GATE_RC)"
    fi

    G=$((G + 1))
done

status "loop finished: $MAX_GENS generations done, champion $(basename "$(champion)")"
